#!/bin/bash
# Begin LSF Directives
#BSUB -P AST149
#BSUB -W 0:05
#BSUB -nnodes 1
#BSUB -J ics_2048
#BSUB -o ics_2048.o%J
#BSUB -e ics_2048.e%J
#BSUB -alloc_flags "smt4"

module load gsl
module load hdf5

export WORK_DIR=/ccs/home/bvilasen/cosmo_tools/ics/send_jobs
export CODE_DIR=/ccs/proj/ast149/code
cd /gpfs/alpine/proj-shared/ast149/cosmo_sims/cholla
date

export OMP_NUM_THREADS=48
CODE_DIR/music/MUSIC /ccs/home/bvilasen/cosmo_tools/ics/music_parameter_files/ics_2048_dm_enzo_50Mpc.conf > run_output.log |sort 
