#!/bin/bash
#SBATCH --job-name=sph_grid      # Job name
#SBATCH --partition=cpuq             # queue for job submission
#SBATCH --mail-type=ALL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=brvillas@ucsc.edu   # Where to send mail
#SBATCH --ntasks=512                  # Number of MPI ranks
#SBATCH --nodes=13                    # Number of nodes
#SBATCH --ntasks-per-node=40         # How many tasks on each node
#SBATCH --time=05:00:00              # Time limit hrs:min:sec
#SBATCH --output=sph_grid_%j.log     # Standard output and error log

pwd; hostname; date

echo "Running program on $SLURM_JOB_NUM_NODES nodes with $SLURM_NTASKS total tasks, with each node getting $SLURM_NTASKS_PER_NODE running on cores."

mpirun -N 512 --map-by ppr:40:node  python /data/groups/comp-astro/bruno/cosmo_tools/analysis/sph/sph_to_grid.py

date
